In [27]:
import torch
import numpy as np

In [26]:
x = torch.rand(2, 2, dtype=torch.double)
y = torch.rand(2, 2, dtype=torch.double)

z = torch.div(x, y)
print(z)
z[:, 1]

tensor([[4.7522, 2.5298],
        [0.3647, 0.9787]], dtype=torch.float64)


tensor([2.5298, 0.9787], dtype=torch.float64)

In [30]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(device)
    y = torch.ones(5, device=device)
    x = torch.rand(5)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

cuda
tensor([1.8805, 1.1933, 1.4666, 1.3523, 1.1387], device='cuda:0')
tensor([1.8805, 1.1933, 1.4666, 1.3523, 1.1387], dtype=torch.float64)


In [35]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)

    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [54]:
weights = torch.ones(4, requires_grad=True)
optimizer = torch.optim.SGD([weights], lr=0.01)
optimizer.step()
optimizer.zero_grad()

## Autograd

In [90]:
x = torch.tensor([3.2, 6.4, 5.1, 6.7, 12, 12, 32 ,34 ,23, 23, 4])
y = torch.tensor([2.0, 3.0, 4.0, 5.0, 45, 45, 2, 5, 6, 7, 8])

w = torch.tensor(4.0, requires_grad=True)

def train(x, y, w, iterations=10):
    for i in range(iterations):
        for xi, yi in zip(x, y):
            # forward pass and compute the loss
            y_hat = w * xi
            loss = (y_hat - yi)**2

            # backward pass	
            loss.backward()

            # update weights
            with torch.no_grad():
                w -= 0.001 * w.grad

            # zero the gradients
            w.grad.zero_()
    return w

w1 = train(x, y, w, iterations=10)
w2 = train(x, y, w, iterations=100)
w3 = train(x, y, w, iterations=1000)

for w in [w1, w2, w3]:
    print(f'Prediction after training: f(3.2) = {w * 3.2:.3f}')
    print(w)


Prediction after training: f(3.2) = 1.184
tensor(0.3700, requires_grad=True)
Prediction after training: f(3.2) = 1.184
tensor(0.3700, requires_grad=True)
Prediction after training: f(3.2) = 1.184
tensor(0.3700, requires_grad=True)
